// Right pane (Precession view): cartoon Earth close-up.
//
// Sunlight is FIXED from the left (a fixed orbital position); the whole
// planet — globe, axis, rings — precesses under it with the axial share of
// Δϖ (retrograde, same sign as scene.js), so the axis rocks ±ε relative to
// the light over the precession cycle: the season at this fixed orbital
// position flips between NH-summer-like and NH-winter-like (γ = 0 is
// June-solstice-like for the NH). This pane is dedicated to the visual
// story of axial precession; the NH-summer distance / insolation story
// lives in summerview.js.
//
// The globe mesh lives INSIDE the tilt group so the texture's poles stay on the
// physical axis; texture lon 0 faces the camera at γ = 0 (t = −1000 kyr).

import * as THREE from 'three';
import { makeGlowTexture, makeStars } from './scene.js';
import { AXIAL_SHARE } from './insolation.js';

const R = 2.2;              // globe radius (scene units)
const RING_R = R * 1.006;   // rings float just above the surface
const CAM_POS = new THREE.Vector3(0, 2.6, 8.4);
const CAM_LOOK = new THREE.Vector3(-0.55, -0.25, 0); // globe sits up-right, HUD bottom-left
const RING_SEGS = 64;
const TWO_PI = Math.PI * 2;

// fixed sunlight: from the left, slightly toward the viewer, in the orbital plane
const SUN_DIR = new THREE.Vector3(-0.85, 0, 0.53).normalize();
const ALPHA_S = Math.atan2(SUN_DIR.x, SUN_DIR.z); // tilt azimuth: axis leans toward the sun
// SphereGeometry maps texture u=0.5 (lon 0 for equirect maps) to +x; rotate the
// globe so lon 0 faces the camera (+z) at γ = 0, given the tilt group's azimuth
const TEX_LON0 = -Math.PI / 2 - ALPHA_S;

// Latitude ring: circle of radius RING_R·cosφ at height RING_R·sinφ around +y
// (built in tilt-group local space, so it tilts with the axis)
function latRing(color, opacity) {
  const pos = new Float32Array(RING_SEGS * 3);
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  const line = new THREE.LineLoop(geo, new THREE.LineBasicMaterial({
    color, transparent: true, opacity, depthWrite: false,
  }));
  line.userData.pos = pos;
  return line;
}

function setLat(line, phi) {
  const pos = line.userData.pos;
  const r = RING_R * Math.cos(phi);
  const y = RING_R * Math.sin(phi);
  for (let i = 0; i < RING_SEGS; i++) {
    const a = (i / RING_SEGS) * TWO_PI;
    pos[i * 3] = r * Math.cos(a);
    pos[i * 3 + 1] = y;
    pos[i * 3 + 2] = r * Math.sin(a);
  }
  line.geometry.attributes.position.needsUpdate = true;
}

export class EarthView {
  constructor(canvas, data) {
    this.data = data;
    this.pi0 = data.pi[0]; // reference ϖ for the precession split (as scene.js)

    this.renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

    this.scene = new THREE.Scene();
    this.scene.add(makeStars(400, 60, 0.35));

    this.camera = new THREE.PerspectiveCamera(38, 1, 0.1, 200);
    this.camera.position.copy(CAM_POS);
    this.camera.lookAt(CAM_LOOK);

    // Key light = Sun, from the left (fixed); fill + ambient kept faint so
    // the night side stays clearly dark against the day side
    this.sunLight = new THREE.DirectionalLight(0xfff7e0, 1.35);
    this.sunLight.position.copy(SUN_DIR).multiplyScalar(10);
    this.scene.add(this.sunLight);
    const fill = new THREE.DirectionalLight(0xdbeafe, 0.08);
    fill.position.copy(CAM_POS);
    this.scene.add(fill);
    this.scene.add(new THREE.HemisphereLight(0x93c5fd, 0x0b1226, 0.06));

    this._buildEarth();

    this._resize = this._resize.bind(this);
    this._ro = new ResizeObserver(this._resize);
    this._ro.observe(canvas.parentElement);
    this._resize();
  }

  _buildEarth() {
    // earthGroup carries the axial precession (rotation.y = γ); tiltGroup inside
    // leans the axis toward the fixed sun by the obliquity
    this.earthGroup = new THREE.Group();
    this.tiltGroup = new THREE.Group();
    this.tiltGroup.rotation.order = 'YXZ';
    this.tiltGroup.rotation.y = ALPHA_S;

    // Flat cartoon texture generated by tools/make_earth_texture.py (land-sea
    // mask from the three.js r160 specular map); falls back to the plain
    // cartoon blue while loading or if missing
    this.globeMat = new THREE.MeshLambertMaterial({ color: 0x3b82f6 });
    new THREE.TextureLoader().load('lib/textures/earth_cartoon_2048.png', (t) => {
      t.colorSpace = THREE.SRGBColorSpace;
      this.globeMat.map = t;
      this.globeMat.color.set(0xffffff);
      this.globeMat.needsUpdate = true;
    });
    const globe = new THREE.Mesh(new THREE.SphereGeometry(R, 64, 48), this.globeMat);
    globe.rotation.y = TEX_LON0; // lon 0 faces the camera at γ = 0
    this.tiltGroup.add(globe);

    const axisGeo = new THREE.BufferGeometry().setFromPoints([
      new THREE.Vector3(0, -R * 1.45, 0),
      new THREE.Vector3(0, R * 1.45, 0),
    ]);
    this.tiltGroup.add(new THREE.Line(axisGeo, new THREE.LineBasicMaterial({ color: 0xfbbf24 })));

    // only the equator survives as a ring
    this.equator = latRing(0x93c5fd, 0.45);
    setLat(this.equator, 0);
    this.tiltGroup.add(this.equator);

    this.earthGroup.add(this.tiltGroup);

    const atmTex = makeGlowTexture([
      [0, 'rgba(147, 197, 253, 0.45)'],
      [0.4, 'rgba(147, 197, 253, 0.14)'],
      [1, 'rgba(147, 197, 253, 0)'],
    ]);
    const atm = new THREE.Sprite(new THREE.SpriteMaterial({
      map: atmTex, transparent: true, depthWrite: false,
    }));
    atm.scale.set(R * 2.6, R * 2.6, 1);
    this.earthGroup.add(atm);

    this.scene.add(this.earthGroup);
  }

  _resize() {
    const el = this.renderer.domElement.parentElement;
    const w = el.clientWidth;
    const h = el.clientHeight;
    if (w === 0 || h === 0) return;
    this.renderer.setSize(w, h, false);
    this.camera.aspect = w / h;
    this.camera.updateProjectionMatrix();
  }

  update(index) {
    const pi = this.data.pi[index];
    const obl = this.data.obl[index];
    const dw = pi - this.pi0;

    // sunlight fixed; the whole planet precesses (retrograde, same sign as scene.js)
    this.earthGroup.rotation.y = -AXIAL_SHARE * dw;
    this.tiltGroup.rotation.x = obl;
    this.renderer.render(this.scene, this.camera);
  }
}
